### PR TITLE
Playlist scrollbar

### PR DESCRIPTION
**Pull request by FreaxMATE**
put playlist into a scrollbar to view long playlists

### CODE REVIEW

**Review by mbkma — COMMENTED** [review]
```
(ojo:2950): GLib-GObject-WARNING **: 23:06:19.804: invalid cast from 'GtkListBox' to 'GtkBox'

(ojo:2950): Gtk-WARNING **: 23:06:19.807: Could not find signal handler 'on_ojo_playlist_box_row_activated'.  Did you compile with -rdynamic?

(ojo:2950): Gtk-CRITICAL **: 23:06:30.305: gtk_list_box_insert: assertion 'GTK_IS_LIST_BOX (box)' failed
```

**Comment by mbkma** [comment]
This PR should only have 2 commits and PR #15 only 1 commit.

**Comment by FreaxMATE** [comment]
> ```
> (ojo:2950): GLib-GObject-WARNING **: 23:06:19.804: invalid cast from 'GtkListBox' to 'GtkBox'
> 
> (ojo:2950): Gtk-WARNING **: 23:06:19.807: Could not find signal handler 'on_ojo_playlist_box_row_activated'.  Did you compile with -rdynamic?
> 
> (ojo:2950): Gtk-CRITICAL **: 23:06:30.305: gtk_list_box_insert: assertion 'GTK_IS_LIST_BOX (box)' failed
> ```

This is not the case when I compile and run it. Perhaps you corrupted your source code when switching branches. Try it again with a new clone.

**Comment by mbkma** [comment]
I tried it again with a new clone; same issues remain and no playlist is displayed.

**Comment by mbkma** [comment]
ok, my fault, I think I forgot that I had to install ojo again, now it works

**Review by mbkma — APPROVED** [review]
Good work!

**Pull request merged**
