### PR TITLE
Meson build system

### PR DESCRIPTION
**Pull request by FreaxMATE**
Install Meson build system https://mesonbuild.com/ with
`sudo apt install meson ninja-build` on debian

To build ojo run
`meson build`
`cd build`
`ninja`

installation works, too
`sudo ninja install`
however, unfortunately somehow it does not work when starting ojo from menu unlike starting it from the terminal. This may be caused by something in the .desktop file.

### CODE REVIEW

**Comment by mbkma** [comment]
I can approve meson with ninja installation works just fine, gsettings works to remember current settings; After PR #12 is merged you could do a rebase and then we can merge this PR. Nicely done!
EDIT: after reboot I got a menu launcher and starting from menu works.
Screenshot at 2019-11-14 18-26-35

**Comment by mbkma** [comment]
I got a segfault while opening movies and music
```
Thread 1 "ojo" received signal SIGSEGV, Segmentation fault.
0x00007ffff76cf2d2 in ?? () from /lib/x86_64-linux-gnu/libgdk-3.so.0
(gdb) backtrace
#0  0x00007ffff76cf2d2 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#1  0x00007ffff770554e in gdk_x11_window_get_xid ()
    at /lib/x86_64-linux-gnu/libgdk-3.so.0
#2  0x0000555555558e86 in ojo_player_media_open
    (list=0x5555559f12b0 = {...}, n_tracks=3, add=0) at ../src/ojo-player.c:129
#3  0x0000555555559ba1 in on_ojo_filechooser_open_clicked ()
    at ../src/ojo-window.c:102
```

**Comment by FreaxMATE** [comment]
Opening music as movies works fine on my Manjaro and my Debian installation. But has it worked for you before?
Does it make a difference when replacing line 129 ojo-player.c with:
`   libvlc_media_player_set_xwindow(ojo_player->media_player, gdk_x11_window_get_xid(gtk_widget_get_window(GTK_WIDGET(drawing_area)))) ;`

**Comment by mbkma** [comment]
> Opening music as movies works fine on my Manjaro and my Debian installation. But has it worked for you before?
> Does it make a difference when replacing line 129 ojo-player.c with:
> ` libvlc_media_player_set_xwindow(ojo_player->media_player, gdk_x11_window_get_xid(gtk_widget_get_window(GTK_WIDGET(drawing_area)))) ;`

No, the same issue still remains. It happens when I open a file, whether I run the already installed ojo or build/src/ojo. In ojo/master I dont have any issues.

**Review by mbkma — DISMISSED** [review]
Everything is fine now. I updated my system (I didn't for a long time) and now it works! Seems that it was a bug somewhere else (maybe in gdk). Good work!

**Comment by FreaxMATE** [comment]
Now I experienced https://github.com/FreaxMATE/Ojo/pull/13#issuecomment-554749138 as well. We tried to get xid of drawing_area before it was actually realized, which caused some random behaviour. 45e7dd1 fixes this.

**Review by mbkma — APPROVED** [review]
I don't have time to test every detail, but in a quick test everything seems to work fine. Well done!

**Pull request merged**
