### PR TITLE
File filter

### PR DESCRIPTION
**Pull request by FreaxMATE**
add a filter allowing only audio and video files to be opened from gtkfilechooser

### CODE REVIEW

**Review by mbkma — COMMENTED** [review]
when opening a pdf:
```
[mp3float @ 0x7f6a00dcff80] Header missing
[00007f6a00dd3d60] main decoder error: buffer deadlock prevented
```
and it gets opened like a music file with length 3:45 minutes.

when opening a folder:
```
************************************************
**                                            **
**  No css library available. See             **
**  /usr/share/doc/libdvdread4/README.css     **
**  for more information.                     **
**                                            **
************************************************
libdvdread: Couldn't find device name.
libdvdread:DVDOpenFilePath:findDVDFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdread:DVDOpenFilePath:findDVDFile /VIDEO_TS/VIDEO_TS.BUP failed
libdvdread: Can't open file VIDEO_TS.IFO.
libdvdnav: vm: failed to read VIDEO_TS.IFO
```
and it gets opened with no control and the slider missing.

**Comment by FreaxMATE** [comment]
> when opening a pdf:
> 
> ```
> [mp3float @ 0x7f6a00dcff80] Header missing
> [00007f6a00dd3d60] main decoder error: buffer deadlock prevented
> ```
> 
> and it gets opened like a music file with length 3:45 minutes.
> 

This happens when opening from command line with filename as argument?

> when opening a folder:
> 
> ```
> ************************************************
> **                                            **
> **  No css library available. See             **
> **  /usr/share/doc/libdvdread4/README.css     **
> **  for more information.                     **
> **                                            **
> ************************************************
> libdvdread: Couldn't find device name.
> libdvdread:DVDOpenFilePath:findDVDFile /VIDEO_TS/VIDEO_TS.IFO failed
> libdvdread:DVDOpenFilePath:findDVDFile /VIDEO_TS/VIDEO_TS.BUP failed
> libdvdread: Can't open file VIDEO_TS.IFO.
> libdvdnav: vm: failed to read VIDEO_TS.IFO
> ```
> 
> and it gets opened with no control and the slider missing.

Ok, opening folders has neither worked before I will try to fix this.

**Comment by mbkma** [comment]
> This happens when opening from command line with filename as argument?

No this happened selecting a pdf in the file chooser (which should not be possible at all).
From command line with 
`ojo ~/Documents/test.pdf`
I get the result:
`WARNING: open_media() in vlcPlayer.c: could not get track description`
and ojo gets stuck.

**Comment by mbkma** [comment]
ok, my fault, I think I forgot that I had to install ojo again, now it works.

**Review by mbkma — CHANGES_REQUESTED** [review]
You should delete "data/org.github.FreaxMATE.Ojo.glade~"

**Review by mbkma — APPROVED** [review]
Well done!
Note: This does not work for folders yet.

**Pull request merged**
