### PR TITLE
port to glade

### PR DESCRIPTION
**Pull request by mbkma**
Hi there,

I ported Ojo to Glade. So it still has a lot of drawbacks, like the progress bar is not functional and buttons are missing, but you are at least able to start a video.
I suggest we leave this PR a work in progress, until it is in a reasonable state, but if you want to add buttons, etc, do it in the glade branch please.

### CODE REVIEW

**Review by FreaxMATE — COMMENTED** [review]
Look my edit

**Comment by mbkma** [comment]
please test again, now it should work

**Comment by mbkma** [comment]
could you revert your last commit, please? I think that is what introduced the merge conflicts. It should be
``git revert 16c13c6850c8d2883c0dd6aba4c5a14b5d6ce13e``

**Comment by mbkma** [comment]
To test, you have to remove the git-symbols from the last commit.

When you tested the code and if you agree, I will merge this PR . Then we can work in the main branch again.

**Review by FreaxMATE — APPROVED** [review]
well done!

**Pull request merged**
